language: java
sudo: false
install: true

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=TraningCenter2018-2019_A_D_Ilyina_first_task -Dsonar.organization=traningcenter2018-2019 -Dsonar.host.url=https://sonarcloud.io  -Dsonar.login=87b4de68a6b2150d4e50462a66970b09678fe2c7

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

