:numbered:
== Пользовательский интерфейс

Поскольку приложение является консольным, взаимодействие между пользователем и игрой осуществляется с помощью текстового ввода-вывода.

В игре есть всего два типа ввода: команды и входные данные для кроссворда.

Все *команды* в игре представлены парой _[Номер команды] Команда_. Например:
----
[1] Играть  [2] Конфигурировать  [3] Помощь  [4] Выход
----

Пользователю предлагается ввести номер, после чего соответсвующая команда выполняется.

Входные данные для кроссворда делятся, в свою очередь, на четыре типа:

. *Размеры поля* - пара целочисленных положительных значений, задающих размеры кроссворда (в ячейках).
+
Пример:
+
----
10
15
----
. *Ограничения* - числовые значения координат, показывающие, в какие ячейки кроссворда нельзя вписать символ. Могут иметь вид _Чило Число_ (ограничить одну ячейку) или _Чило Число - Чило Число_ (ограничить все ячейки в заданном диапазоне).
+
Пример:
+
----
3 7
1 1 - 3 5
----
. *Подсказки* - набор слов, из которых генерируется кроссворд. В случае канадского кроссворда это пара _Слово - Подсказка_.
+
Пример:
+
----
Земля - Планета, на которой мы живём
----
. *Ответы* - символы или слова, которые игрок хочет внести в кроссворд. Могут иметь вид _Число Число - Символ_ (добавить символ на заданную числами позицию) или _Число - Слово_ (добавить слово, имеющее заданный номер).
+
Пример:
+
----
6 10 - а
14 - зима
----
