[plantuml, diagrams, png]
....
interface GameTerminal {
  +void drawUI()
  +void initialize()
  +String getNextInput()
}

class CrosswordTerminal {
  -Game game
  --
}

CrosswordTerminal .up.|> GameTerminal
CrosswordTerminal -() Game
....
