=== Crossword Game

link:../diagrams/class-game.puml[Game Class Diagram]

[caption=""]
.interface Game
====
void play():: Метод команды "Играть".
void configure():: Метод команды "Конфигурировать".
void getHelp():: Метод команды "Помощь".
void quit():: Метод команды "Выйти".
void deleteCrossword():: Метод команды "Удалить кроссворд".
void createCrossword():: Метод команды "Создать кроссврд".
void saveCrossword():: Метод команды "Сохранить кроссврд".
void checkCrossword():: Метод команды "Проверить кроссврд".
void handleInput(String input):: Метод, обрабатывающий входные данные в зависимости от состояния игры.
====

[caption=""]
.class CrosswordGame
====
private State state:: Текущее состояние игры.
private Crossword crossword:: Ссылка на объект кроссворда.
private void pickCrossword(int number):: Метод выбора кроссворда из хранилища по номеру.
private void addSymbol(int[2] position, char symbol)::
Метод добавления одного символа в кроссворд.
private void addWord(int[2][2] position, String word):: Метод добавления слова в кроссворд.
public State getState():: Геттер поля state.
====

[caption=""]
.enum State
====
Одно из возможных состояний игры
====

Данный модуль связывает интерфейс, с которым непосредственно взаимодействует пользователь, и логику игры.

Интерфейс Game имеет ряд сигнатур методов, соответсвующих командам игры, и метод обработки ввода (handleInput(...)). Данный метод через модуль Main получает ввод от терминала, после чего обрабатывает его и совершает соответствующие внутреннему состоянию игры действия.

Использование состояний (State) оправдывается тем, что ход игры, вообще говоря, является линейным. В целом его можно описать таким циклом: +

*_Вывести информацию на экран -> Получить входные данные от пользователя -> Обработать входные данные -> Вывести информацию на экран_*

Именно поэтому число всевозможных состояний игры будет конечным, и в зависимости от этого можно изменять её поведение.
